version: 2


jobs:
  deploy-job:
    steps:
      -run:
        name: antes
        command:
           echo "Hola mundo"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: main

