version: 2.1


jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: main

